### ISSUE TITLE
Far side Amb spikes up when leaving map

### ISSUE THREAD

**Issue by ghost** [gap9269/SDDSound#161]

**Comment by ghost** [comment]
This might be due to the crossfade between maps not expecting an ambience to already be at 0.  Should probably try changing the crossfade so it goes from current val -> 0 instead of starting from the .vol file value

**Comment by gap9269** [comment]
It does fade out from the current volume. When you say leaving map, do you
mean the far side or the quad?

**Comment by ghost** [comment]
the second quad map that has 2 ambiences.  The far side ambience is silent when you're at the bottom, but when you leave it jumps back up and then quickly fades out.  Jarring

**Comment by gap9269** [comment]
The same happens when you leave the quad. I actually know why it does it,
too. There is only one ambience volume in the game, but I multiply that
specific one based on your vertical height. But when you change maps it's
only taking into account the Sound.AmbienceVolume, which is whatever the
user has it set as, which makes all ambience shoot up to that volume and
then fade out. This is only an issue when there is ambience that changes
volume in the map.

The solution is to go into the PlayAmbience for these maps and stop the
farside ambience if you're so low in the map that you can't hear it.

**Comment by ghost** [comment]
That sounds like it'll work

On Monday, May 18, 2015, Gary notifications@github.com wrote:

> The same happens when you leave the quad. I actually know why it does it,
> too. There is only one ambience volume in the game, but I multiply that
> specific one based on your vertical height. But when you change maps it's
> only taking into account the Sound.AmbienceVolume, which is whatever the
> user has it set as, which makes all ambience shoot up to that volume and
> then fade out. This is only an issue when there is ambience that changes
> volume in the map.
> 
> The solution is to go into the PlayAmbience for these maps and stop the
> farside ambience if you're so low in the map that you can't hear it.
> 
> On Tue, May 19, 2015 at 1:09 AM, Miles Flanagan <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > the second quad map that has 2 ambiences. The far side ambience is silent
> > when you're at the bottom, but when you leave it jumps back up and then
> > quickly fades out. Jarring
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gap9269/SDDSound/issues/161#issuecomment-103339437.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gap9269/SDDSound/issues/161#issuecomment-103347745.

## 

Miles Flanagan
Composer, Sound Designer for Games
milesflanaganmusic.com
