### ISSUE TITLE
Wwise Bank Changes

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#236]
- Add attack_stop for cymbal, eatball. Probably every enemy, honestly.

**Comment by ghost** [comment]
- Huboard comments can't be deleted, and that's super lame

**Comment by ghost** [comment]
- this is awkward

**Comment by ghost** [comment]
- With the issues resolved, streamed file banks can now be loaded all the time since it's not loading the audio files into memory, so keep ambience.bnk, music.bnk, and cutscenes.bnk loaded from the start.
- sounds from ambience and music will play automatically, sounds from cutscenes need to be prepared since they are not streamed, but still loose so you can load assets individually.  Once cutscenes.bnk is loaded initially, just call LoadEvents() and load what you need. ClearPreparedEvents() will unload all media from any prepared events.  UnloadPreparedEvents() will unload specific events (using an array and # like Load).
- Added Stop_Object event in global.bnk that stops all the sounds coming from an object, so we don't have to worry about every enemy having all kinds of interrupt events and cluttery garbage like that.  I should have thought of that months ago.
- Added music.  all the tracks are their names in lower case and without spaces (bloodonthecourt_play, etc).  Every track has a _play (instant) event and a _stop (fade out) event right now.  Also a Stop_Music, Pause_Music, and Resume_Music event that will affect all tracks globally.  Music is streamed from disc, so load the bank at the start and never unload it as it uses almost no memory.  
- You can control the music volume using Music_Volume RTPC.  Changed all the options menu RTPCs to start with Options_ so you know not to mess with them.  These RTPC's are additive, on a scale of 0 to 100, and default to 100.  Setting both to 50 will result in 25, except the curve isn't exactly a percentage like the text file was. Pretty close, though.  Slew rate of _500/s_. _Basically instant but won't pop if you set it straight to something._
- Added music_bathroom_enter and _exit events in music.bnk to make the music get filtered and pan left.  Fades back and forth over about a second or so.  Could do similar events for other stuff later, like pause screen, inventory menu, death, glass flask trap, whatevs.
- Captain sax should be able to sync with music now. You'll have to see how I did it in the test project in the repo because there's some math in there so you can set a timer for when to start the loop.  There's currently a divide-by-zero crash that i should probably fix that only happens if you try to set the timer before the music starts (if the track has a pickup before bar 1).  You should just check for that before doing the math so it doesnt crash for now until I figure out how to estimate time until bar 1 from the pickup.  As a reminder it's captain_sax_loop_intro when he spawns and captain_sax_full_loop_start when you get to the downbeat.  The tempo is set internally every time you play a track so it already knows that.
- Music is uncompressed now and can resume from pause again but ambience is still Vorbis.  Let me know if the resume function is broken for ambience I would be so sad.
- Added Music_Playback_Speed RTPC because why not.  Slow slew rate so you can hear it spool up and down.  Very silly, please use everywhere all the time.  Set in %, can go from 25 to 400.
- CHANGE ALL REFERENCES TO WWISESHARPSOUNDPOSITION AND LISTENERPOSITION TO WwiseSharpTransform (same format as ListenerPosition). Wwise2016 consolidate both into one unified struct.  Objects don't use orientation at all so just pass {x,y,z,0,0,0,0,0,0}.  When I convert it in the wrapper I just ignore it anyway and pass 0,1,0 so it's always normalized and doesn't yell at me as much.  Also you don't have to ever call InitReverb() again it's still there but it doesn't do anything because they changed how plugins work.
- Every music track has _stop, _play, _pause, and _resume, which trigger instantly.  Just call using trackname+"_pause" like you normally would.  Also have _fadein_play, _fadein_resume, _fadeout_pause, and fadeout_stop for map transition crossfades since you can't control the volume of each track directly (they are playing from the same object so the volume rtpc will affect both).  If the crossfades don't sound right at first I can keep messing with them until they sound smooth, but it's just an option.  DO NOT USE the global Pause_Music and Resume_Music events anymore because that was probably causing the weird transition problems.  Stop_Music is fine but will purge any pause tracks.
- Level up triggers were fucking up the music so try using currentTrack+"_pause" and _resume now that you can do that.
- Added a WwiseSharpTransform Constructor that just takes x,y,z position and normalizes all the orientation bs we don't use
